services:
  - type: web
    name: olympiad-site-1
    runtime: python
    branch: main
    buildCommand: |
      pip install -r requirements.txt
      python3 manage.py collectstatic --noinput
      python3 manage.py migrate
      python3 manage.py init_admin
    startCommand: gunicorn config.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: YOOKASSA_SHOP_ID
        value: ""
      - key: YOOKASSA_SECRET_KEY
        value: ""
      - key: PYTHON_VERSION
        value: 3.12.3
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings.prod
      - key: DJANGO_DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: your-service.onrender.com
      - key: EMAIL_HOST_USER
        value: vsemnayka@gmail.com
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: EMAIL_USE_TLS
        value: "True"
      - key: DEFAULT_FROM_EMAIL
        value: vsemnayka@gmail.com
      - key: ROBOKASSA_DEMO
        value: "True"
    disks:
      - name: media
        mountPath: /opt/render/project/src/media
        sizeGB: 1
